### ISSUE TITLE
index.js file not found

### ISSUE THREAD

**Issue by javadnikbakht** [samatix/data-stream#6]
There must be index.js file in static folder but there isn't.

**Comment by crabel99** [comment]
Noticed that too, there is nothing to tie the websocket into the front end.

**Comment by samatix** [comment]
I've just added the file to the repo

**Comment by samatix** [comment]
File added https://github.com/samatix/data-stream/commit/d7e4182c4ce123ed60ee6a5e9b3f38497763c67e
